# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instamodel',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
